### ISSUE TITLE
Pico Pinout Project Outline & Goals

### ISSUE THREAD

**Issue by Gadgetoid** [pinout-xyz/pico.pinout.xyz#1]
Preview the work-in-progress here: https://pico.pinout.xyz/

## Mission Statement

To make an *accessible* alternative to the static, graphical Raspberry Pi Pico pinout.

Must:
1. Be easy for beginners to read/filter/facet
2. Be at least *somewhat* compatible with screen readers (help, I don't know what I'm doing!)
3. Make some accommodations for colour impaired users.
4. Be simple, straight-forward but visually beautiful

## Roadmap
* [x] Replaced hot-linked Pi image with a lovely scalable SVG
* [x] Alt-text! - "Your Raspberry Pi Pico, orientated with the USB port facing upwards and sitting on its little pin legs."
* [ ] Figure out aria labelling to introduce each pin as "GP0, first pin down on the left-hand side"
* [ ] Add expansion boards somehow. Might need to write a tool to generate the pinout HTML... hand-crafting could get very tiresome!

## How you can help

1. Hit "Sponsor". No. Really. :laughing: 
2. Lend your expertise- are there better ways to lay this out semantically, support screen readers, etc?
3. Just try it out and see how it works for you! - https://pico.pinout.xyz/

**Comment by justin-pierce** [comment]
Don't see a license -- are you ok with derivatives etc?

**Comment by Gadgetoid** [comment]
Ooh that's a good point. I placed Pinout.xyz under CC-BY-NC mostly because I didn't want to encourage lousy hackjobs and straight up screenshots, but that all seemed to happen regardless. Additionally the non-commercial clause prevented contributions by employees of certain orgs who were unable to work with those terms for nebulous legal reasons.

I guess CC-BY-SA is probably most reflective of what I want people to do with this stuff.
